Update deployment workflow

diff --git a/.github/workflows/azure-vm-deploy.yml b/.github/workflows/azure-vm-deploy.yml
--- a/.github/workflows/azure-vm-deploy.yml
+++ b/.github/workflows/azure-vm-deploy.yml
@@ -11,18 +11,17 @@ jobs:
 
     steps:
     - name: Deploy via SSH
-      uses: appleboy/ssh-action@v1.0.3
-      with:
-        host: ${{ secrets.AZURE_VM_HOST }}
-        username: ${{ secrets.AZURE_VM_USERNAME }}
-        key: ${{ secrets.AZURE_VM_SSH_KEY }}
-        script: |
-          # Stop and remove the existing container if it is running
-          docker stop express-containerized || true
-          docker rm express-containerized || true
-          
-          # Pull the latest public image from Docker Hub
-          docker pull zeelz/express-containerized:${{ vars.IMAGE_TAG }}
-          
-          # Run the updated container
-          docker run -d -p 3000:3000 --name express-containerized --platform linux/amd64 -e "DB_USER=${{ vars.DB_USER }}" -e "DB_HOST=${{ vars.DB_HOST }}" -e "DB_NAME=postgres" -e "DB_PORT=${{ vars.DB_PORT }}" zeelz/express-containerized:${{ vars.IMAGE_TAG }}
+      run: |
+        apk add --no-cache openssh-client
+
+        echo "ssh-keyscan to known_hosts"
+        ssh-keyscan -H "${{ secrets.AZURE_VM_HOST }}" >> /tmp/known_hosts
+        chmod 400 "${{ secrets.AZURE_VM_SSH_KEY }}" # stored as file
+
+        ssh -o StrictHostKeyChecking=no -i "${{ secrets.AZURE_VM_SSH_KEY }}" "${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}" " &&
+
+        docker stop express-containerized || true &&
+        docker rm express-containerized || true &&
+        docker pull zeelz/express-containerized:${{ vars.IMAGE_TAG }} &&
+        docker run -d -p 3000:3000 --name express-containerized --platform linux/amd64 -e "DB_USER=${{ vars.DB_USER }}" -e "DB_HOST=${{ vars.DB_HOST }}" -e "DB_NAME=postgres" -e "DB_PORT=${{ vars.DB_PORT }}" zeelz/express-containerized:${{ vars.IMAGE_TAG }} &&
+        "
